name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
      - run: flutter pub get
        working-directory: packages/telegram_login
      - run: flutter analyze
        working-directory: packages/telegram_login

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
      - run: flutter pub get
        working-directory: packages/telegram_login
      - run: flutter test
        working-directory: packages/telegram_login
